### ISSUE TITLE
有没有横向滑动加载更多？

### ISSUE THREAD

**Issue by leocreater** [VinsonGuo/android-kline#13]

**Comment by leocreater** [comment]
加个好友一起讨论来

**Comment by YuanJianTing** [comment]
+1

**Comment by happyHou** [comment]
https://my.oschina.net/u/2002921/blog/673994

**Comment by VinsonGuo** [comment]
在这个月月底之前会加入这个功能

**Comment by leocreater** [comment]
月底再来看看，即使我都写出来了

**Comment by VinsonGuo** [comment]
@leocreater 欢迎往本项目pull request来完善它😊

**Comment by VinsonGuo** [comment]
已增加这个功能

**Comment by leocreater** [comment]
看了下，加载更多一次之后 mKLineView.setOnLoadMoreListener(null);  下次还能继续加载更多吗

**Comment by VinsonGuo** [comment]
可以的 因为没有更多的测试数据，所以设置为null把加载更多禁用了
