### ISSUE TITLE
发现一个bug,setdata(),多次后缩放比例失调，第二次setdata就会出现

### ISSUE THREAD

**Issue by leocreater** [VinsonGuo/android-kline#14]

**Comment by VinsonGuo** [comment]
init系列方法只能使用一次，不建议多次调用

**Comment by hezhipengzipp** [comment]
如果不调用init方法，那我15分钟切换到30分钟，该怎么使用

**Comment by hezhipengzipp** [comment]
经过群主提点：
![image](https://user-images.githubusercontent.com/19803305/44513908-459c4b00-a6f1-11e8-9900-9a8960801b48.png)
