### ISSUE TITLE
分时图怎么加载空数据

### ISSUE THREAD

**Issue by yuliangC** [VinsonGuo/android-kline#18]
分时图应该先把时间固定吧，比如21:00至15:00应该先标记在x轴上，然后有多少数据就显示多少数据。但是现在是一屏的数据如果有了两百多条就已经铺满全屏了。中午12点就已经满了一屏，这样别人还以为没有数据了。。。正常应该是中午12点只有半屏，下午的数据是空的没有画，但是x轴上我能看到15:00，大佬这个要怎么实现啊？

**Comment by VinsonGuo** [comment]
setCount方法设置你需要的数量即可
